# Generated by Django 4.1.7 on 2023-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbBackupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_month', models.CharField(default='*', max_length=255)),
                ('schedule_day', models.CharField(default='*', max_length=255)),
                ('schedule_hour', models.CharField(default='*', max_length=255)),
                ('schedule_minute', models.CharField(default='*', max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
