# Generated by Django 4.0.4 on 2023-02-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSettings', '0003_emailconfigmodel_smsconfigmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfigModel',
        ),
        migrations.DeleteModel(
            name='SMSConfigModel',
        ),
    ]
