# Generated by Django 4.1.7 on 2023-03-05 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appSettings', '0004_delete_emailconfigmodel_delete_smsconfigmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
