# Generated by Django 4.0.4 on 2023-01-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0002_remove_activitylog_action_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='action_IP',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='action_agent_info',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
