# Generated by Django 4.0.4 on 2023-03-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBLConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantId', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('testMerchantId', models.CharField(max_length=255)),
                ('testPassword', models.CharField(max_length=255)),
                ('testMode', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
