# Generated by Django 4.1.7 on 2023-03-07 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_stripeconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=12)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Due', 'Due'), ('Paid', 'Paid'), ('Canceled', 'Canceled'), ('Failed', 'Failed')], default='Due', max_length=50)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.currencymodel')),
            ],
        ),
    ]
