# Generated by Django 4.1.7 on 2023-03-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='currency',
            field=models.CharField(max_length=10),
        ),
    ]
