# Generated by Django 4.1.7 on 2023-03-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_ordermodel_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
