# Generated by Django 4.1.7 on 2023-03-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_ordermodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
