# Generated by Django 4.1.7 on 2023-03-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewaymodel',
            name='access_key',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentgatewaymodel',
            name='api_key',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentgatewaymodel',
            name='test_access_key',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentgatewaymodel',
            name='test_api_key',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentgatewaymodel',
            name='test_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewaymodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
