# Generated by Django 4.1.7 on 2023-03-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_delete_eblconfig_delete_stripeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewaymodel',
            name='payment_gateway_class',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
