# Generated by Django 4.0.4 on 2023-02-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_emailschedulemodel_notificationmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='emailschedulemodel',
            options={'ordering': ['-schedule_time']},
        ),
        migrations.AlterModelOptions(
            name='smsschedulemodel',
            options={'ordering': ['-schedule_time']},
        ),
        migrations.AddField(
            model_name='emailschedulemodel',
            name='mail_subject',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailschedulemodel',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailschedulemodel',
            name='text',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smsschedulemodel',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smsschedulemodel',
            name='text',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
