# Generated by Django 4.0.4 on 2023-02-08 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_emailschedulemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailschedulemodel',
            name='schedule_day',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='emailschedulemodel',
            name='schedule_month',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='broadcast_day',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='broadcast_month',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='smsschedulemodel',
            name='schedule_day',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='smsschedulemodel',
            name='schedule_month',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
