# Generated by Django 4.0.4 on 2023-02-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_emailschedulemodel_schedule_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='sent',
        ),
    ]
