# Generated by Django 4.0.4 on 2023-02-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_remove_notificationmodel_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailschedulemodel',
            name='schedule_time',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='broadcast_time',
        ),
        migrations.RemoveField(
            model_name='smsschedulemodel',
            name='schedule_time',
        ),
        migrations.AddField(
            model_name='emailschedulemodel',
            name='schedule_hour',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AddField(
            model_name='emailschedulemodel',
            name='schedule_minute',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='broadcast_hour',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='broadcast_minute',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AddField(
            model_name='smsschedulemodel',
            name='schedule_hour',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AddField(
            model_name='smsschedulemodel',
            name='schedule_minute',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailschedulemodel',
            name='schedule_day',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailschedulemodel',
            name='schedule_month',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='broadcast_day',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='broadcast_month',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AlterField(
            model_name='smsschedulemodel',
            name='schedule_day',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AlterField(
            model_name='smsschedulemodel',
            name='schedule_month',
            field=models.CharField(default='*', max_length=255),
        ),
    ]
