# Generated by Django 4.1.7 on 2023-03-05 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0007_remove_emailschedulemodel_schedule_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedulemodel',
            name='receiver',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailschedulemodel',
            name='send_to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='receiver',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='send_to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smsschedulemodel',
            name='receiver',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smsschedulemodel',
            name='send_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
