# Generated by Django 4.1.7 on 2023-03-16 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_remove_notificationmodel_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notification.notificationsubsribe'),
            preserve_default=False,
        ),
    ]
