# Generated by Django 4.1.7 on 2023-03-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_notificationmodel_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='is_onetime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='notification_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
