# Generated by Django 4.0.4 on 2023-01-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='debug',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='email',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='storage_used',
            field=models.CharField(choices=[('local', 'local'), ('aws', 'aws'), ('gcp', 'gcp')], default='local', max_length=50),
        ),
    ]
