# Generated by Django 4.0.4 on 2023-03-15 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='issue_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issue_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=256)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('description', models.TextField(max_length=512)),
                ('is_open', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('re-assigned', 're-assigned'), ('processing', 'processing'), ('completed', 'completed'), ('delivered', 'delivered'), ('rejected', 'rejected')], max_length=64)),
                ('is_registered_user', models.BooleanField(default=False)),
                ('priority', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], max_length=64, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_approved_by', to=settings.AUTH_USER_MODEL)),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket', to='support.issuetypesmodel')),
                ('support_agent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_support_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'permissions': (('can_assign_support_agent', 'Can Assign Support Agent'), ('can_change_ticket_status', 'Can Change Ticket Status'), ('can_change_ticket_priority', 'Can Change Ticket Priority'), ('can_change_ticket_due_date', 'Can Change Ticket Due Date'), ('can_close_ticket', 'Can Close Ticket'), ('can_delete_ticket', 'Can Delete Ticket'), ('can_reply_ticket_comments', 'Can Reply Ticket Comments')),
            },
        ),
        migrations.CreateModel(
            name='TicketLogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('action_types', models.CharField(choices=[('created', 'created'), ('agent_assinged', 'agent_assinged'), ('agent_re-assigned', 'agent_re-assigned'), ('changed_status', 'changed_status'), ('changed_priority', 'changed_priority'), ('changed_due_date', 'changed_due_date'), ('close_ticket', 'close_ticket')], max_length=64)),
                ('details', models.TextField(blank=True, max_length=512, null=True)),
                ('ticket_status', models.CharField(max_length=256)),
                ('ticket_priority', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_creators_email', models.EmailField(max_length=256)),
                ('support_agent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_logs_support_agent', to=settings.AUTH_USER_MODEL)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_logs', to='support.ticketmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('comment', models.CharField(max_length=256)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_comments_author', to=settings.AUTH_USER_MODEL)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to='support.ticketmodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_comments_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
