# Generated by Django 4.0.4 on 2023-03-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticketmodel_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcommentsmodel',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
