# Generated by Django 4.0.4 on 2023-03-19 08:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_ticketmodel_options_alter_ticketmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlogsmodel',
            name='action_types',
            field=models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('deleted', 'deleted'), ('close_ticket', 'close_ticket'), ('open_ticket', 'open_ticket')], max_length=64),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
